<?php

namespace Database\Seeders\Modules;

use App\Models\ContractTemplate;
use App\Models\ContractType;
use App\Models\DocumentAcknowledgment;
use App\Models\DocumentCategory;
use App\Models\DocumentTemplate;
use App\Models\Employee;
use App\Models\EmployeeContract;
use App\Models\HrDocument;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Storage;

/**
 * The demo's Documents & Contracts data. HR documents get a small generated text file in place of
 * the demo's uploads; employees are matched by email, then name.
 */
class DocumentSeeder extends Seeder
{
    public function run(): void
    {
        $data = File::json(database_path('demo/documents.json'), JSON_THROW_ON_ERROR);
        $companyId = User::query()->where('email', 'company@example.com')->value('id');

        foreach ($data['categories'] as $row) {
            $category = DocumentCategory::query()->firstOrCreate(['name' => $row['name']], [...$row, 'created_by' => $companyId]);
            // Categories seeded before icons existed pick theirs up.
            if ($category->icon === 'Folder') {
                $category->update(['icon' => $row['icon']]);
            }
        }

        $categories = DocumentCategory::query()->pluck('id', 'name');

        foreach ($data['documents'] as $row) {
            $path = 'hr-documents/seed-'.$row['file_name'];

            if (! Storage::disk('local')->exists($path)) {
                Storage::disk('local')->put($path, "{$row['title']} (version {$row['version']})\n\n{$row['description']}\n\nPlaceholder file generated by the demo seeder.\n");
            }

            HrDocument::query()->firstOrCreate(['title' => $row['title']], [
                ...Arr::except($row, ['category']),
                'category_id' => $categories[$row['category']] ?? null,
                'file_path' => $path,
                'file_type' => 'text/plain',
                'file_size' => Storage::disk('local')->size($path),
                'uploaded_by' => $companyId,
                'created_by' => $companyId,
            ]);
        }

        $documents = HrDocument::query()->pluck('id', 'title');

        foreach ($data['acknowledgments'] as $row) {
            $userId = $this->userId($row);

            if ($userId && isset($documents[$row['document']])) {
                DocumentAcknowledgment::query()->firstOrCreate(
                    ['document_id' => $documents[$row['document']], 'user_id' => $userId],
                    [...Arr::except($row, ['document', 'employee_email', 'employee_name']), 'assigned_by' => $companyId],
                );
            }
        }

        foreach ($data['document_templates'] as $row) {
            DocumentTemplate::query()->firstOrCreate(['name' => $row['name']], [
                ...Arr::except($row, ['category']),
                'category_id' => $categories[$row['category']] ?? null,
                'created_by' => $companyId,
            ]);
        }

        foreach ($data['contract_types'] as $row) {
            ContractType::query()->firstOrCreate(['name' => $row['name']], [...$row, 'created_by' => $companyId]);
        }

        $contractTypes = ContractType::query()->pluck('id', 'name');

        foreach ($data['contract_templates'] as $row) {
            ContractTemplate::query()->firstOrCreate(['name' => $row['name']], [
                ...Arr::except($row, ['contract_type']),
                'contract_type_id' => $contractTypes[$row['contract_type']] ?? null,
                'created_by' => $companyId,
            ]);
        }

        foreach ($data['employee_contracts'] as $row) {
            $userId = $this->userId($row);
            $employeeId = $userId ? Employee::query()->where('user_id', $userId)->value('id') : null;

            if ($employeeId) {
                EmployeeContract::query()->firstOrCreate(['contract_number' => $row['contract_number']], [
                    ...Arr::except($row, ['employee_email', 'employee_name', 'contract_type']),
                    'employee_id' => $employeeId,
                    'contract_type_id' => $contractTypes[$row['contract_type']] ?? null,
                    'created_by' => $companyId,
                ]);
            }
        }
    }

    /**
     * @param  array{employee_email: string, employee_name: string}  $row
     */
    private function userId(array $row): ?int
    {
        $id = User::query()->where('email', $row['employee_email'])->value('id')
            ?? User::query()->where('name', $row['employee_name'])->value('id');

        return $id === null ? null : (int) $id;
    }
}
